/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/e36wnzvkSoz
 */
import { Button } from "@/components/ui/button"

export function SignInOutV0() {
  return (
    <div className="flex justify-center space-x-4">
      <Button className="transition-colors duration-200 hover:bg-blue-700" variant="default">
        Login
      </Button>
      <Button className="transition-colors duration-200 hover:bg-green-700" variant="outline">
        Sign up
      </Button>
    </div>
  )
}
